![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np

print(np.__version__)


2.3.0


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = np.array((0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
print(my_array)

#otra forma

my_array2 = np.arange(10)
print(my_array2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
my_array3 = np.array(((True, True, True),(True, True, True),(True, True, True)))
print(my_array3)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [27]:
x = my_array.copy() #x quiero convertirlo en array impares

impares_mask = x % 2 != 0

print(impares_mask)

impares = x[impares_mask]

print(impares)


[False  True False  True False  True False  True False  True]
[1 3 5 7 9]


In [33]:
#ejemplo con pares (para ver si lo he entendido)

otra_array = np.array((2,8,5,6,9,4,7,3))
print(otra_array)

pares_mask = otra_array % 2 == 0

pares= otra_array[pares_mask]
print(pares)


[2 8 5 6 9 4 7 3]
[2 8 6 4]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [49]:
otra_array = np.array((2,8,5,6,9,4,7,3))
print(otra_array)

impares_mask = otra_array % 2 != 0
print(impares_mask)

otra_array[impares_mask]=-1

print(otra_array)




[2 8 5 6 9 4 7 3]
[False False  True False  True False  True  True]
[ 2  8 -1  6 -1  4 -1 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:
otra_array = np.array((2,8,5,6,9,4,7,3))
print(otra_array)

impares_menos1 = np.where(otra_array %2 !=0, -1, otra_array)
print(impares_menos1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [50]:
my_array = np.array((0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [64]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print("Imprime a:", a)
print("Imprime b:", b)

concatena_a_b_verticalmente = np.vstack((a,b))

print("concatenados:", "\n", concatena_a_b_verticalmente)



Imprime a: [[0 1 2 3 4]
 [5 6 7 8 9]]
Imprime b: [[1 1 1 1 1]
 [1 1 1 1 1]]
concatenados: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [65]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print("Imprime a:", a)
print("Imprime b:", b)

concatena_a_b_horizontalmente = np.hstack((a,b))

print("concatenados:", "\n", concatena_a_b_horizontalmente)

Imprime a: [[0 1 2 3 4]
 [5 6 7 8 9]]
Imprime b: [[1 1 1 1 1]
 [1 1 1 1 1]]
concatenados: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

elementos_comunes = np.intersect1d(a,b)
print(elementos_comunes)



[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [68]:
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [73]:
my_array = np.arange(10)
print(my_array)
nuevo_array = my_array * 10
print(nuevo_array)


[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [76]:
my_matrix = np.array(((1,2,3), (4,5,6), (7,8,9)))

print(my_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [84]:
un_array = np.arange(50)
print(un_array)
secuencia = un_array[1:50:3]
print(secuencia)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [99]:
x = np.arange(4.0,1.0,-0.25)
print(x)


[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

In [103]:
import matplotlib.pyplot as plt

# img = plt.imread (blablabla)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [107]:
array_nuevo = np.array((4,5,6,7))
print(array_nuevo)

array_nuevo.reshape(2,2)

[4 5 6 7]


array([[4, 5],
       [6, 7]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [110]:
secuencia_aleatoria = np.random.rand(4,5,3)
print(secuencia_aleatoria)

[[[0.4624418  0.73494419 0.95492495]
  [0.45435383 0.5911115  0.9103946 ]
  [0.90386509 0.57354772 0.71198992]
  [0.91674222 0.62845935 0.86336022]
  [0.08918987 0.52441055 0.93369376]]

 [[0.93491271 0.37512493 0.26452078]
  [0.09487515 0.59903467 0.1403748 ]
  [0.30672472 0.03483786 0.46038896]
  [0.72626201 0.09995248 0.4969934 ]
  [0.57220194 0.89070467 0.75700215]]

 [[0.65510827 0.08926513 0.17634685]
  [0.91978787 0.96574214 0.31130978]
  [0.51817359 0.67960636 0.17371329]
  [0.06174411 0.77589735 0.59066376]
  [0.82474037 0.7610216  0.77321636]]

 [[0.31204498 0.35240841 0.22444128]
  [0.43902685 0.37652832 0.20371847]
  [0.65973606 0.69118335 0.19669957]
  [0.71715302 0.61067988 0.67431108]
  [0.37881015 0.37706501 0.29831877]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [115]:
matriz = np.array((False,False,False,False,False, False,False, False, False,False,))

print(matriz)

matriz_2 = matriz.reshape(2,5)
print(matriz_2)

[False False False False False False False False False False]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [126]:
# Elementos Array = 5*2*6 = 60
# Dimensiones = 3
"""
Elementos dimension:
Dimensión 1 = 5 Elementos
Dimensión 2 = 2 Elementos
Dimensión 3 = 6 Elementos
"""


'\nElementos dimension:\nDimensión 1 = 5 Elementos\nDimensión 2 = 2 Elementos\nDimensión 3 = 6 Elementos\n'