![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
x = np.arange(1,21)
x2 = x.reshape(4,5)
print(x2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
x2_invertida = x2[::-1, ::-1]
print(x2_invertida)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [12]:
x = np.arange(1,21)
x2 = x.reshape(4,5)
print(x2)

x3 = np.vsplit(x2, 2)
print(x3)
primera_parte = x3[0]
print(primera_parte)

resultado = primera_parte[:, :2]
print("resultado", "\n", resultado)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
resultado 
 [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [34]:
x = np.arange(1,21)
x2 = x.reshape(4,5)
print(x2)

x4 = x2[0][::2]
print(x4)
print(x2)
x5 = x2[2][::2]
print(x5)

solucion = np.stack((x4,x5))
print("solucion:","\n", solucion)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 3 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[11 13 15]
solucion: 
 [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [42]:
x = np.arange(1,21)
x2 = x.reshape(4,5)
print(x2)

x6 = x2[:3:, ::-1]
print("solución", "\n", x6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
solución 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [46]:
#1ª forma

x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x7 = x == "Loro"
print(x7)

x8 = x[x7]
print("solución", x8)

[ True False False  True False]
solución ['Loro' 'Loro']


In [55]:
x9 = x[:5:3]
print("solucion:", x9)

solucion: ['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [60]:
secuencia = np.arange(20)
print(secuencia)

secuencia2 = secuencia.reshape(2,2,5)
print("Solución:", "\n", secuencia2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Solución: 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [65]:
x = np.arange(1,21)
x2 = x.reshape(4,5)
print(x2)

x10 = x2[::-1, ::-1]
print("solución", "\n", x10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
solución 
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [76]:
array10 = np.array([0,0,0,0,0,0,0,0,0,0])
print(array10)
print("solución espacio memoria", array10.nbytes)

array10[3]=1
print(array10)

[0 0 0 0 0 0 0 0 0 0]
solución espacio memoria 80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [79]:
array11= np.arange(10,50)
array12 =array11[49::-1]
print("solución:",array12)

solución: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [ ]:
#ojoooooo queremos vectos no tupla de arrays
vector = np.array([1,2,0,0,4,0])
indices = np.where(vector != 0)
print("solución:",indices[0] )

#alternativa
vector = np.array([1,2,0,0,4,0])
indice_2 =np.nonzero(vector)
print("solución2", indice_2[0])



solución: [0 1 4]
solución2 [0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [96]:
y = np.random.randint(0,100, size=(10,10))
ymin = y.min()
print(ymin)
ymax = y.max()
print(ymax)

4
96


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [109]:
x = np.random.randint(0,100, size= 30)
print(x)

media = x.mean()
print(media)


[57 50  9 22 43 53 70 41 15 85 47  8 27 15 76 82 15 15 31 64 25 74 48 10
 71 72 71 57 51 28]
44.4


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [112]:
array_cuadrado = np.array([[1,1,1], [1,0,1], [1,1,1]])
print(array_cuadrado)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [118]:
fila_1 = np.array([0, 1, 0, 1, 0, 1, 0, 1])
fila_2 = 1 - fila_1
tablero = np.vstack([fila_1, fila_2] * 4)  # repite el par fila1,fila2 cuatro veces y apila verticalmente
print(tablero)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [113]:
array01 = np.array([[0, 1], 
                   [1, 0]])

solucion = np.tile(array01, (4, 4))  # repite 4 veces filas y 4 veces columnas
print(solucion)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [120]:
matriz3 = np.random.rand(5,5)
print(matriz3)
media = np.mean(matriz3)
print(media)
desviacion = np.std(matriz3)
print(desviacion)
matriz_estandarizada = (matriz3 - media) / desviacion
print(matriz_estandarizada)

[[0.32755382 0.33777696 0.20477676 0.41610051 0.51870619]
 [0.41970573 0.18259889 0.62800011 0.23386248 0.82126713]
 [0.59812351 0.7696141  0.89143918 0.5225656  0.19050264]
 [0.4138572  0.94648613 0.79086611 0.12422064 0.03519947]
 [0.47571444 0.17689287 0.50701586 0.08474866 0.17672974]]
0.4317729889921475
0.26032927657670235
[[-0.40033596 -0.36106593 -0.87195814 -0.06020252  0.33393557]
 [-0.04635383 -0.95714972  0.7537651  -0.76023147  1.49615959]
 [ 0.63900043  1.29774537  1.7657107   0.34876065 -0.92678916]
 [-0.06881974  1.97716196  1.37938048 -1.18139746 -1.52335352]
 [ 0.16879181 -0.97906821  0.28902961 -1.33302077 -0.97969483]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [122]:
#1. Crea una secuencia de números que vayan del 0 al 10.

secuencia = np.arange(11)
print(secuencia)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [123]:
#2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1

nuevo_array = secuencia.copy()
nuevo_array[(nuevo_array >= 3) & (nuevo_array <= 8)] = -1
print(nuevo_array)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [125]:
#3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

array_negado = secuencia.copy()
array_negado[(array_negado >= 3) & (array_negado <= 8)] *= -1
print(array_negado)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')